CREATE DATABASE PBL;
CREATE TABLE infoPBL (Name VARCHAR(50), Age INT, Gender VARCHAR(10), ContactNumber VARCHAR(20), Address VARCHAR(100), Email VARCHAR(50), CinemaNumber VARCHAR(5), SeatNumber VARCHAR(5), Time VARCHAR(10), Date DATETIME);
SELECT * FROM infoPBL;
alter table infoPBL alter column Date VARCHAR (30);
CREATE TABLE surveyPBL (Name VARCHAR(50), Q1 VARCHAR(5), Q2 VARCHAR(5), Q3 VARCHAR(5), Q4 VARCHAR(5), Q5 VARCHAR(5), Q6 VARCHAR(5), Q7 VARCHAR(5), Q8 VARCHAR(5), Q9 VARCHAR(5), Q10 VARCHAR(5), Q11 VARCHAR(5));
SELECT * FROM surveyPBL;