CREATE DATABASE PBL;
CREATE TABLE infoPBL (Name VARCHAR(50), Age INT, Gender VARCHAR(10), ContactNumber VARCHAR(20), Address VARCHAR(100), Email VARCHAR(50), CinemaNumber VARCHAR(5), SeatNumber VARCHAR(5), Time VARCHAR(10), Date DATETIME);
SELECT * FROM infoPBL;